<?php
/**
 * Copyright 2014 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright 2014 Google Inc. All rights reserved
 * @license http://www.apache.org/licenses/LICENSE-2.0.txt Apache-2.0
 * @package Benchmarks
 */

/**
 * This example shows how you can get a performance benefit by compiling an
 * expensive PHP function.
 */

use ReckiCT\Jit;

require_once __DIR__ . '/../vendor/autoload.php';

/**
 * A Fibonacci generator!!!
 *
 * This is a recursive implementation. Very slow on PHP, and MUCH faster
 * when compiled.
 *
 * We only need this function as a fallback, since we're compiling with the IR,
 * this won't be touched until the benchmark.
 *
 * @param int $n The number of the sequence to generate
 *
 * @return int the fibonacci number!
 */
function fibo($n)
{
    if ($n < 2) {
        return 1;
    }

    return fibo($n - 1) + fibo($n - 2);
}

/**
 * This is the intermediate representation that was cached from a previous generation
 * of fibo.
 *
 * It can be generated by the following command:
 *
 * $ir = Jit::getInstance()->getFunctionIr($functionName);
 */
$ir = <<<'ENDIR'
function fibo long
param $1 long
begin
const $2 numeric 2
var $3 bool
< $1 $2 $3
jumpz $3 @1
const $4 numeric 1
return $4
return
label @1
const $5 numeric 1
var $6 numeric
- $1 $5 $6
var $7 long
recurse $6 $7
const $8 numeric 2
var $9 numeric
- $1 $8 $9
var $10 long
recurse $9 $10
var $11 numeric
+ $7 $10 $11
return $11
return
end
ENDIR;

/**
 * Compile the function using the JITFU extension!
 *
 * This is extremely cheap, since no analysis needs to happen. All that happens is the IR
 * is turned into JIT-Fu instructions (which are then compiled by libjit).
 */
$func = Jit::getInstance()->compileIrJitFu($ir, 'fibo');

/**
 * Now let's benchmark the two implementations!
 *
 * If you don't have JitFu installed, then both should be equal.
 */
benchmark("fibo", "PHP");
benchmark($func, "ReckiCT");

/**
 * A very light weight benchmark tool, which runs the code 100,000 times.
 *
 * For very simple functions like the one we are testing here, we don't expect
 * a lot of gain (if any), since the overhead of the functional call will dominate
 * the runtime.
 *
 * @param callable $func  The function to benchmark
 * @param string   $label The label of the test, for output
 *
 * @return void
 */
function benchmark(callable $func, $label)
{
    $start = microtime(true);
    $result = $func(30);
    $end = microtime(true);
    printf("%s completed fibo(30)==$result in %01.4F seconds\n", $label, $end - $start);
}
